#!/bin/bash

# Добавляем путь к yabai, чтобы он был доступен при запуске через launchd
export PATH="/opt/homebrew/bin:$PATH"

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 40 
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 4 

# -- mouse settings --


# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
# yabai -m mouse_drop_action swap


yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_shadow                off
# yabai -m config window_border                on
# yabai -m config active_window_border_color   0xff775759
# yabai -m config window_animation_duration    0.5            
yabai -m config window_animation_easing      ease_out_circ  

# это главное:
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0

# и главное:
# yabai -m config window_float                 off

# yabai -m config external_bar all:12:0

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^VmVApp$" manage=off
yabai -m rule --add app="^Google Chrome for Testing$" manage=off
