if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$HOME/.local/bin":$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# ==============================  
# Подключение темы 
# ==============================  
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
   git
  #  zsh-autosuggestions
   web-search
   )

source $ZSH/oh-my-zsh.sh

# Переменные 
SPRINTHOST="a0791978@141.8.192.58"
BEGET_VPS="root@62.217.178.7"

# # # Мои подключения
# for file in ~/.private/**/*; do
#   source "$file"
# done

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(/opt/homebrew/bin/brew shellenv)"


resketch() {
    killall sketchybar
    sketchybar &
}

# window() {
#     if [[ "$1" -eq 1 ]]; then
#         yabai &
#         skhd &
#         sketchybar &
#     elif [[ "$1" -eq 0 ]]; then
#         killall yabai skhd sketchybar
#     else
#         echo "Usage: window 1 (start) or window 0 (stop)"
#     fi
# }

window() {
    if [[ "$1" -eq 1 ]]; then
        yabai &
        skhd &
    elif [[ "$1" -eq 0 ]]; then
        killall yabai skhd
    else
        echo "Usage: window 1 (start) or window 0 (stop)"
    fi
}

newthemezsh() {
  rm -rf ~/.p10k.zsh
  rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  exec zsh
  p10k configure
}

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

__ip() {
    echo "VPN IP:    |  $(curl -s ifconfig.me)" 
    echo "Родной IP: |  $(curl -s --interface en0 https://ifconfig.me )" }

speedcheck() {
  result=$(speedtest --simple)
  ping=$(echo "$result" | grep "Ping" | awk '{print $2 " " $3}')
  download=$(echo "$result" | grep "Download" | awk '{print $2 " " $3}')
  upload=$(echo "$result" | grep "Upload" | awk '{print $2 " " $3}')
  echo "Ping: $ping | Download: $download | Upload: $upload"
}

allsizeapp() {
    echo "-- Само приложение --"  
    du -sh /Applications/$1.app 
    echo "\n"
    echo "-- User Library --"  
    find ~/Library -iname "*$1*" 2>/dev/null -exec du -sh {} \;
}

brewsizeformulae() {
    echo "-- Само приложение $1 --"  
    du -sh $(brew --prefix)/Cellar/$1/*
    echo "\n"
    echo "-- Его зависимости --"  
    du -sh $(brew --prefix)/Cellar/$1/*
}

# Вывести оставшееся место на диске
disk() {
  echo "Real free:   $(df -h / | awk 'NR==2 {print $4}')"
  diskutil info / | awk -F": " "/Free Space/{printf \"%d Gi\n\", \$2}"
}

# Отобразить или скрыть файлы и директории на рабочем столе
finderw() {
  current=$(defaults read com.apple.finder CreateDesktop 2>/dev/null)

  if [[ "$current" == "1" || "$current" == "true" ]]; then
    defaults write com.apple.finder CreateDesktop false
  else
    defaults write com.apple.finder CreateDesktop true
  fi

  killall Finder
}

# ==============================  
# Алиасы 
# ==============================  

alias l="eza --group-directories-first --git --tree --icons --level=1"
alias ll="eza --group-directories-first  --git  --tree -l --icons --level=1"
alias la="eza --group-directories-first  --git  --tree -la --icons --level=1"
alias ps1-abe="open https://gam.onl/psx/oddworld-abe-oddysee.html#game"
alias sprinthost="ssh a0791978@141.8.192.58"
alias inv='nvim $(fzf -m --preview="bat --color=always {}")'

alias ncdu='ncdu --color=dark'

alias __vpn1="scutil --nc start 'VmVApp'"
alias __vpn0="scutil --nc stop 'VmVApp'"

alias __googlesheetmoney="open 'https://docs.google.com/spreadsheets/d/1GwkgPXEuBy_Js1tSaBIDLb6IOE7pU_FP47e5w-zJYDA/edit?gid=0#gid=0'"
alias y.metrika="open 'https://metrika.yandex.ru'"
alias f.garmonya="open 'https://docs.google.com/spreadsheets/d/191erh3kSXClVJkRLB0tIUBwJcFLAkpsCMn9IUDXYQmc/edit?gid=1101889799#gid=1101889799'"


alias newuser="sudo sysadminctl -addUser evgenypopelaev -fullName \"Евгений Попеляев\" -password qwerty"
alias deleteuser="sudo sysadminctl -deleteUser evgenypopelaev -removeHomeDirectory"
alias szsh="source ~/.zshrc"
alias dud="du -sh"
alias dua="du -h"
alias shlvl="echo Shell уровень - $SHLVL"

alias fzf="fzf --preview 'bat --style=numbers --color=always {}'"

# ============================== 
# Ссылки в браузере
# ============================== 

alias browser-avito="open 'https://www.avito.ru'"
alias browser-ollama="open 'https://ollama.com/search'"
alias browser-rutracker="open 'https://rutracker.org/'"
alias browser-youtube="open 'https://www.youtube.com'"

alias nvim-zero='XDG_CONFIG_HOME=$HOME/.config/nvim-zero \
XDG_DATA_HOME=$HOME/.local/share/nvim-zero \
XDG_CACHE_HOME=$HOME/.cache/nvim-zero \
nvim'

source <(fzf --zsh)
alias vv='NVIM_APPNAME=nvim-alt nvim'
alias avim='NVIM_APPNAME=avim nvim'
alias cvim='NVIM_APPNAME=cvim nvim'
export MANPATH=~/man/ru:$MANPATH
export LANG=ru_RU.UTF-8